# Generated by Django 4.2.7 on 2023-11-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cngstations',
            name='STATION_CITY',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
