# Generated by Django 4.2.7 on 2023-11-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cngstations_station_postalcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cngstations',
            name='STATION_STATE_CODE',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
