# Generated by Django 4.2.1 on 2023-11-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customeusers_delete_customeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customeusers',
        ),
    ]
